### ISSUE TITLE
Error: Unable to create serialized game state

### ISSUE THREAD

**Issue by andrewd18** [trekcc-ops/gemp-stccg#131]
As seen on main at commit `a7b5144c2181bc90d3da4d8fcb86f9c90afe0268`.

When I load a game, the chat is spammed with "Unable to create serialized game state". The game continues as expected.

![image](https://github.com/user-attachments/assets/7e9b9c7a-ccee-40d3-8074-5c2d7d2e4b28)

The nohup.out file contains no other logs about what might be happening. I bisected this down to merge #127; whatever it is doesn't happen until after that.

**Comment by datanoh** [comment]
I'm unable to reproduce this error on my end. Do you have any additional context?
- When you say "load game", do you mean initially launching a new game? Or was this re-entering an in-progress game, or hitting refresh? (If the game was already in progress, what was going on in the game when this happened?)
- Decks / format of the game?

I did push an edit to main to provide some error context in the nohup file when this error is triggered.

**Comment by datanoh** [comment]
Still no success reproducing it on my end. Do you have an example deck / format you've used where you've run into this issue? My best guess is that there's some weird kind of card causing this issue, like a multi-affiliation personnel or something. Probably causing an NPE that's getting buried by the Json serialization.

It'd be helpful to have a starting point.

**Comment by andrewd18** [comment]
Still happening on main, the new log code indicates it's an NPE.

```
gemp_app_1  | Unable to create serialized game state
gemp_app_1  | com.fasterxml.jackson.databind.JsonMappingException: [no message for java.lang.NullPointerException]
gemp_app_1  |   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._wrapAsIOE(DefaultSerializerProvider.java:531) ~[web.jar:?]
gemp_app_1  |   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:504) ~[web.jar:?]
gemp_app_1  |   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341) ~[web.jar:?]
gemp_app_1  |   at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3364) ~[web.jar:?]
gemp_app_1  |   at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:422) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.gamestate.GameStateSerializer.serialize(GameStateSerializer.java:62) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.gamestate.GameStateSerializer.serialize(GameStateSerializer.java:1) ~[web.jar:?]
gemp_app_1  |   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:502) ~[web.jar:?]
gemp_app_1  |   at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:341) ~[web.jar:?]
gemp_app_1  |   at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4799) ~[web.jar:?]
gemp_app_1  |   at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4040) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.gamestate.GameEvent.serializeGameState(GameEvent.java:253) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.gamestate.GameEvent.setCardData(GameEvent.java:167) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.gamestate.GameEvent.<init>(GameEvent.java:86) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.gamestate.GameState.sendCreatedCardToListener(GameState.java:353) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.gamestate.GameState.sendCreatedCardToListener(GameState.java:332) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.gamestate.GameState.addCardToZone(GameState.java:323) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.gamestate.ST1EGameState.addMissionLocationToSpaceline(ST1EGameState.java:110) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.actions.playcard.SeedMissionCardAction.seedCard(SeedMissionCardAction.java:159) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.actions.playcard.SeedMissionCardAction.nextAction(SeedMissionCardAction.java:143) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.processes.TurnProcedure.executeNextSubaction(TurnProcedure.java:67) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.processes.TurnProcedure.carryOutPendingActionsUntilDecisionNeeded(TurnProcedure.java:38) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.game.DefaultGame.carryOutPendingActionsUntilDecisionNeeded(DefaultGame.java:212) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.game.CardGameMediator.playerAnsweredNew(CardGameMediator.java:235) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.async.handler.GameRequestHandler.updateGameState(GameRequestHandler.java:91) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.async.handler.GameRequestHandler.handleRequest(GameRequestHandler.java:64) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.async.handler.RootUriRequestHandler.handleRequest(RootUriRequestHandler.java:74) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.async.GempukkuHttpRequestHandler.channelRead0(GempukkuHttpRequestHandler.java:82) ~[web.jar:?]
gemp_app_1  |   at com.gempukku.stccg.async.GempukkuHttpRequestHandler.channelRead0(GempukkuHttpRequestHandler.java:1) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
gemp_app_1  |   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[web.jar:?]
gemp_app_1  |   at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
gemp_app_1  |   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[web.jar:?]
gemp_app_1  |   at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[web.jar:?]
gemp_app_1  |   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[web.jar:?]
gemp_app_1  |   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[web.jar:?]
gemp_app_1  |   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[web.jar:?]
gemp_app_1  |   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[web.jar:?]
gemp_app_1  |   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[web.jar:?]
gemp_app_1  |   at java.lang.Thread.run(Thread.java:1583) [?:?]

```

**Comment by andrewd18** [comment]
To reproduce I'm using decks "Basic Test":
```
DRAW_DECK|101_196,101_197,101_198,101_199,101_200,101_201,101_202,101_205,101_204,101_203,101_206,101_208,101_209,101_211,101_212,101_216,101_215,101_214,101_213,101_217,101_218,101_219,101_220,101_225,101_223,101_222,101_221,101_226,101_229,101_232,101_331,101_332,244_014,127_035,135_011,101_334|SEED_DECK|101_104|MISSIONS|101_194,101_155,101_146,101_150,101_151,101_153
```
and "Basic Test 2"
```
DRAW_DECK|101_312,101_310,101_320,101_329,101_330,101_289,101_290,101_293,101_292,101_297,101_299,101_303,101_300,101_297,101_297,101_300,101_300,101_303,101_303,101_293,101_293,101_320,101_320,101_330,101_330,101_065,101_065,101_065,101_065,101_065,101_357,101_358,116_108,101_362,163_054|SEED_DECK|101_106|MISSIONS|101_148,101_149,101_154,101_158,101_157,101_163
```

**Comment by datanoh** [comment]
Thanks! I'll take a look at it.
