### ISSUE TITLE
Server crash when trying to load a game

### ISSUE THREAD

**Issue by andrewd18** [trekcc-ops/gemp-stccg#99]
Similar to issue #98 , a card was removed from the blueprints in PR #92  (Anaphasic Organism).

Unlike #98, where it errors when I try to create a table, in this case I can create a game and attempt to join it. When I do, I get this crash in the server side.

```
02:02:52.002 [nioEventLoopGroup-3-11] ERROR com.gempukku.stccg.async.GempukkuHttpRequestHandler - Error response for /gemp-stccg-server/hall/1
java.lang.RuntimeException: Card blueprint not found
	at com.gempukku.stccg.gamestate.ST1EGameState.createPhysicalCards(ST1EGameState.java:65) ~[web.jar:?]
	at com.gempukku.stccg.game.ST1EGame.<init>(ST1EGame.java:26) ~[web.jar:?]
	at com.gempukku.stccg.game.ST1EGameMediator.<init>(ST1EGameMediator.java:11) ~[web.jar:?]
	at com.gempukku.stccg.game.GameServer.getCardGameMediator(GameServer.java:181) ~[web.jar:?]
	at com.gempukku.stccg.game.GameServer.createNewGame(GameServer.java:115) ~[web.jar:?]
	at com.gempukku.stccg.hall.HallServer.createGameMediator(HallServer.java:463) ~[web.jar:?]
	at com.gempukku.stccg.hall.HallServer.createGameFromTable(HallServer.java:436) ~[web.jar:?]
	at com.gempukku.stccg.hall.HallServer.joinTableAsPlayer(HallServer.java:243) ~[web.jar:?]
	at com.gempukku.stccg.async.handler.HallRequestHandler.joinTable(HallRequestHandler.java:97) ~[web.jar:?]
	at com.gempukku.stccg.async.handler.HallRequestHandler.handleRequest(HallRequestHandler.java:81) ~[web.jar:?]
	at com.gempukku.stccg.async.handler.RootUriRequestHandler.handleRequest(RootUriRequestHandler.java:74) ~[web.jar:?]
	at com.gempukku.stccg.async.GempukkuHttpRequestHandler.channelRead0(GempukkuHttpRequestHandler.java:82) ~[web.jar:?]
	at com.gempukku.stccg.async.GempukkuHttpRequestHandler.channelRead0(GempukkuHttpRequestHandler.java:1) ~[web.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[web.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[web.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[web.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[web.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[web.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[web.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[web.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868) ~[web.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[web.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[web.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[web.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[web.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[web.jar:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
02:02:52.919 [Thread-1] ERROR com.gempukku.stccg.ServerCleaner - Error while cleaning up a server
java.lang.NullPointerException: Cannot invoke "com.gempukku.stccg.game.CardGameMediator.isDestroyed()" because "cardGameMediator" is null
	at com.gempukku.stccg.hall.TableHolder.removeFinishedGames(TableHolder.java:232) ~[web.jar:?]
	at com.gempukku.stccg.hall.HallServer.cleanup(HallServer.java:476) ~[web.jar:?]
	at com.gempukku.stccg.ServerCleaner$CleaningThread.run(ServerCleaner.java:34) [web.jar:?]
02:02:53.921 [Thread-1] ERROR com.gempukku.stccg.ServerCleaner - Error while cleaning up a server
```

Please investigate why this card does not cause the same deck builder error/table-creation prevention as #98.  Perhaps this is because it is a dilemma, whereas the other one was a mission?

**Comment by andrewd18** [comment]
Testable by creating an empty deck in the db, then using a database editor, opening the Decks table and changing the `contents` column for that row to:
```
SEED_DECK|101_104,101_353,101_354,101_355,101_356,101_353,101_355,101_012,101_014,101_015|DRAW_DECK|155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055,155_055|MISSIONS|101_146,106_003,112_105,155_038,155_041,155_044
```
